spring.application.name=aurea

# ==============================
# JPA / HIBERNATE - COMMON
# ==============================

spring.jpa.open-in-view=false

# ==============================
# JWT - COMMON
# ==============================

aurea.jwt.secret=${AUREA_JWT_SECRET}
aurea.jwt.expiration-seconds=3600
