# ==============================
# DATABASE - PRODUCTION
# ==============================

spring.datasource.url=${AUREA_DB_URL}
spring.datasource.username=${AUREA_DB_USER}
spring.datasource.password=${AUREA_DB_PASSWORD}

# ==============================
# JPA / HIBERNATE - PRODUCTION
# ==============================

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=validate

# ==============================
# AUREA PRODUCTION
# ==============================

aurea.catalog.import.enabled=false
aurea.order.test.enabled=false

# ==============================
# OPENAPI / SWAGGER - DISABLED
# ==============================

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# ==============================
# ERROR INFORMATION
# ==============================

server.error.include-stacktrace=never
server.error.include-message=never