CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    display_order NUMBER,

    CONSTRAINT pk_categories PRIMARY KEY (id)
);


CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(150) NOT NULL,
    category_id NUMBER NOT NULL,
    code VARCHAR2(30),
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    description VARCHAR2(500),

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_code UNIQUE (code),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
);


CREATE TABLE product_prices (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    price NUMBER(10,2) NOT NULL,
    active BOOLEAN NOT NULL,

    CONSTRAINT pk_product_prices PRIMARY KEY (id),

    CONSTRAINT uq_product_prices_product_quantity
        UNIQUE (product_id, quantity),

    CONSTRAINT fk_product_prices_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
);


CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(150) NOT NULL,
    delivery_date DATE,
    delivery_time TIMESTAMP(6),
    requires_delivery BOOLEAN NOT NULL,
    address VARCHAR2(250),
    district VARCHAR2(100),
    delivery_fee NUMBER(10,2) NOT NULL,
    products_subtotal NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    observations VARCHAR2(1000),
    status VARCHAR2(30) NOT NULL,
    source VARCHAR2(30) NOT NULL,
    firebase_document_id VARCHAR2(128),
    legacy_order_number NUMBER,
    legacy_created_at TIMESTAMP(6),
    legacy_updated_at TIMESTAMP(6),
    legacy_payment_method VARCHAR2(100),
    legacy_payment_status VARCHAR2(100),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_orders PRIMARY KEY (id),

    CONSTRAINT uq_orders_firebase_document
        UNIQUE (firebase_document_id)
);


CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER NOT NULL,
    item_type VARCHAR2(20) NOT NULL,
    product_id NUMBER,
    product_price_id NUMBER,
    description_snapshot VARCHAR2(250) NOT NULL,
    quantity NUMBER NOT NULL,
    price_type VARCHAR2(20) NOT NULL,
    reference_price NUMBER(10,2) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    notes VARCHAR2(500),

    CONSTRAINT pk_order_items PRIMARY KEY (id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products (id),

    CONSTRAINT fk_order_items_product_price
        FOREIGN KEY (product_price_id)
        REFERENCES product_prices (id)
);


CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    enabled BOOLEAN NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    username VARCHAR2(100) NOT NULL,

    CONSTRAINT chk_app_users_role
        CHECK (role IN ('ADMIN','DELIVERY','PRODUCCION','VENTAS')),

    CONSTRAINT pk_app_users PRIMARY KEY (id),

    CONSTRAINT uq_app_users_username
        UNIQUE (username)
);